import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#fef7f0',
          100: '#fdecd8',
          200: '#fad5ae',
          300: '#f6b87a',
          400: '#f19543',
          500: '#ed7b20',
          600: '#de6111',
          700: '#b84a10',
          800: '#933c14',
          900: '#793414',
          950: '#411806',
        },
        accent: {
          50: '#f0f7ff',
          100: '#dfeeff',
          200: '#b8ddff',
          300: '#79c2ff',
          400: '#38a3ff',
          500: '#0b84f3',
          600: '#0066d1',
          700: '#0052a9',
          800: '#00468b',
          900: '#003c73',
          950: '#002549',
        },
        gray: {
          50: '#fafaf9',
          100: '#f5f5f3',
          200: '#e7e5e2',
          300: '#d5d3cf',
          400: '#a8a49e',
          500: '#79756e',
          600: '#5c5852',
          700: '#44413c',
          800: '#2a2825',
          900: '#1a1917',
          950: '#0f0e0d',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      fontSize: {
        display: [
          '3.5rem',
          { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '800' },
        ],
      },
      typography: {
        DEFAULT: {
          css: {
            maxWidth: 'none',
            color: '#44413c',
            lineHeight: '1.75',
            fontSize: '1rem',
            h1: {
              color: '#1a1917',
              fontWeight: '700',
              fontSize: '2.25rem',
              lineHeight: '2.5rem',
              letterSpacing: '-0.025em',
              marginTop: '2rem',
              marginBottom: '1rem',
            },
            h2: {
              color: '#1a1917',
              fontWeight: '700',
              fontSize: '1.875rem',
              lineHeight: '2.25rem',
              letterSpacing: '-0.02em',
              marginTop: '2rem',
              marginBottom: '1rem',
            },
            h3: {
              color: '#1a1917',
              fontWeight: '600',
              fontSize: '1.5rem',
              lineHeight: '2rem',
              letterSpacing: '-0.015em',
              marginTop: '1.5rem',
              marginBottom: '0.75rem',
            },
            code: {
              color: '#0b84f3',
              backgroundColor: '#f0f7ff',
              paddingLeft: '0.25rem',
              paddingRight: '0.25rem',
              paddingTop: '0.125rem',
              paddingBottom: '0.125rem',
              borderRadius: '0.25rem',
              fontSize: '0.875rem',
              fontWeight: '500',
            },
            'code::before': {
              content: '""',
            },
            'code::after': {
              content: '""',
            },
            pre: {
              backgroundColor: '#f5f5f3',
              color: '#2a2825',
              borderRadius: '0.75rem',
              padding: '1.25rem',
              overflow: 'auto',
              border: '1px solid #e7e5e2',
            },
            'pre code': {
              backgroundColor: 'transparent',
              color: 'inherit',
              padding: '0',
              borderRadius: '0',
              fontSize: '0.875rem',
            },
            blockquote: {
              borderLeftColor: '#ed7b20',
              borderLeftWidth: '3px',
              fontStyle: 'normal',
              color: '#5c5852',
              backgroundColor: '#fef7f0',
              padding: '0.875rem 1.25rem',
              borderRadius: '0 0.5rem 0.5rem 0',
              margin: '1.5rem 0',
            },
            a: {
              color: '#0b84f3',
              textDecoration: 'underline',
              textDecorationColor: '#b8ddff',
              textUnderlineOffset: '3px',
              transition: 'all 0.15s ease',
              '&:hover': {
                color: '#0066d1',
                textDecorationColor: '#79c2ff',
              },
            },
          },
        },
        invert: {
          css: {
            color: '#d5d3cf',
            h1: { color: '#f5f5f3' },
            h2: { color: '#f5f5f3' },
            h3: { color: '#f5f5f3' },
            code: {
              color: '#38a3ff',
              backgroundColor: '#2a2825',
            },
            pre: {
              backgroundColor: '#0d1117',
              color: '#f0f6fc',
              border: '1px solid #2a2825',
            },
            'pre code': {
              backgroundColor: 'transparent',
              color: 'inherit',
              padding: '0',
              borderRadius: '0',
              fontSize: '0.875rem',
            },
            blockquote: {
              borderLeftColor: '#f19543',
              color: '#d5d3cf',
              backgroundColor: '#2a2825',
            },
            a: {
              color: '#38a3ff',
              textDecorationColor: '#0052a9',
              textUnderlineOffset: '3px',
              '&:hover': {
                color: '#79c2ff',
                textDecorationColor: '#0b84f3',
              },
            },
          },
        },
      },
    },
  },
  plugins: [typography],
};
